cabal-version:      3.0
name:               jenga-backend-servant
version:            0.1.0.0
synopsis:           Backend server for Jenga using Snap + Servant
license:            BSD-3-Clause
build-type:         Simple

library
  exposed-modules:
    Jenga.Backend.Servant

  build-depends:
    , base              >=4.12 && <5
    , bytestring
    , containers
    , data-default
    , jenga-asset-serve-snap
    , jenga-route-servant
    , reflex-effectful
    , servant
    , servant-snap
    , snap-core
    , snap-server
    , text

  hs-source-dirs:   src
  default-language:  Haskell2010

  if arch(javascript) || arch(wasm32)
    buildable: False

  default-extensions:
    ConstraintKinds
    DataKinds
    FlexibleContexts
    FlexibleInstances
    GADTs
    KindSignatures
    MultiParamTypeClasses
    OverloadedStrings
    RankNTypes
    ScopedTypeVariables
    TypeApplications
    TypeFamilies
    TypeOperators
