module Jenga.Command.Deploy.Init
  ( InitOpts (..)
  , optsParser
  , run
  ) where

import Control.Monad (when)
import Options.Applicative hiding (info)
import System.Directory (createDirectoryIfMissing, doesPathExist)
import System.FilePath ((</>))
import System.Which (staticWhich)

import Jenga.Command.Utils (die, info, readProcess_, runProcess, strip)

gitPath :: FilePath
gitPath = $(staticWhich "git")

data InitOpts = InitOpts
  { initDir    :: String
  , initSource :: Maybe String
  }

optsParser :: Parser InitOpts
optsParser = InitOpts
  <$> strArgument (metavar "DIR" <> help "Deployment staging directory to create")
  <*> optional (strArgument (metavar "PROJECT-SOURCE" <> help "Git remote URL or local path (default: origin)"))

run :: InitOpts -> IO ()
run opts = do
  let dir = initDir opts

  exists <- doesPathExist dir
  when exists $ die $ "directory already exists: " <> dir

  projectSource <- case initSource opts of
    Just src -> pure src
    Nothing -> do
      src <- strip <$> readProcess_ gitPath ["remote", "get-url", "origin"]
      if null src
        then die "no project source given and no git remote 'origin' found.\n\
                  \Usage: jenga deploy init <dir> [<git-remote-url-or-path>]"
        else do
          info $ "Detected project source: " <> src
          pure src

  info $ "Initializing deployment directory: " <> dir

  createDirectoryIfMissing True (dir </> "config" </> "backend")
  createDirectoryIfMissing True (dir </> "config" </> "common")
  createDirectoryIfMissing True (dir </> "config" </> "frontend")
  createDirectoryIfMissing True (dir </> "secrets")

  writeFile (dir </> "project_source") (projectSource <> "\n")

  branch <- strip <$> readProcess_ gitPath ["rev-parse", "--abbrev-ref", "HEAD"]
  writeFile (dir </> "project_branch") (branch <> "\n")
  info $ "Project branch: " <> branch

  writeFile (dir </> "config" </> "route_host")      "CHANGEME.example.com\n"
  writeFile (dir </> "config" </> "admin_email")      "admin@example.com\n"
  writeFile (dir </> "config" </> "enable_https")     "true\n"
  writeFile (dir </> "config" </> "frontend_target")  "wasm\n"
  writeFile (dir </> "config" </> "internal_port")    "8000\n"
  writeFile (dir </> "config" </> "base_url")         "/\n"

  writeFile (dir </> "hosts") "# One SSH host per line (user@host or just host for root@)\n"

  writeFile (dir </> "secrets" </> "ssh_key") ""
  runProcess "chmod" ["600", dir </> "secrets" </> "ssh_key"]

  writeFile (dir </> "secrets" </> ".gitignore") "*\n"
  writeFile (dir </> ".gitignore") "secrets/\n"

  writeFile (dir </> "deploy.nix") deployNixTemplate

  runProcess gitPath ["-C", dir, "init", "-q"]
  runProcess gitPath ["-C", dir, "add", "-A"]
  runProcess gitPath ["-C", dir, "commit", "-q", "-m", "Initialize deployment"]

  info $ "Deployment directory initialized: " <> dir
  putStrLn ""
  putStrLn "Next steps:"
  putStrLn $ "  1. Edit " <> dir </> "config/route_host with your domain"
  putStrLn $ "  2. Edit " <> dir </> "config/admin_email with your email"
  putStrLn $ "  3. Copy your SSH private key to " <> dir </> "secrets/ssh_key"
  putStrLn $ "  4. Add target host(s) to " <> dir </> "hosts"
  putStrLn $ "  5. Run: jenga deploy push " <> dir

deployNixTemplate :: String
deployNixTemplate = unlines
  [ "# Generated by jenga deploy init. Customize services.jenga options via config/ files."
  , "{ system ? builtins.currentSystem"
  , ", projectSource"
  , ", projectRev ? null"
  , ", routeHost"
  , ", adminEmail"
  , ", enableHttps ? \"true\""
  , ", frontendTarget ? \"wasm\""
  , ", internalPort ? \"8000\""
  , ", baseUrl ? \"/\""
  , ", backendArgs ? null"
  , ", redirectHosts ? \"\""
  , ", configHash ? \"\""
  , "}:"
  , ""
  , "let"
  , "  src ="
  , "    if builtins.substring 0 1 projectSource == \"/\""
  , "    then builtins.path { path = projectSource; name = \"project-src\"; }"
  , "    else builtins.fetchGit ({"
  , "      url = projectSource;"
  , "      allRefs = true;"
  , "    } // (if projectRev != null then { rev = projectRev; } else {}));"
  , ""
  , "  proj = import src { inherit system; };"
  , ""
  , "  parseHosts = s:"
  , "    builtins.filter (x: x != \"\")"
  , "      (builtins.filter builtins.isString (builtins.split \"\\n\" s));"
  , ""
  , "in proj.server {"
  , "  exe = proj.serverExe.${frontendTarget};"
  , "  inherit routeHost adminEmail baseUrl configHash;"
  , "  enableHttps = enableHttps == \"true\";"
  , "  internalPort = builtins.fromJSON internalPort;"
  , "  backendArgs ="
  , "    if backendArgs != null"
  , "    then backendArgs"
  , "    else \"--port=${internalPort}\";"
  , "  redirectHosts = parseHosts redirectHosts;"
  , "}"
  ]
