cabal-version: 2.4
name: jenga-auth-common
version: 0.1
build-type: Simple

library
  hs-source-dirs: src
  if arch(javascript) || arch(wasm32)
    buildable: False
  build-depends: base
               , aeson
               , base64-bytestring
               , beam-core
               , bytestring
               , containers
               , email-validate
               , lens
               , network-uri
               , mime-mail
               , mime-mail-orphans
               , effectful-core
               , jenga-route-servant
               , rhyolite-account-types
               , signed-data
               , stripe-core
               , text
               , time
  if !impl(ghcjs)
     build-depends: unicode-transforms

  exposed-modules:
        Jenga.Common.Auth
        Jenga.Common.OAuth
        Jenga.Common.BeamExtras
        Jenga.Common.Schema
        Jenga.Common.Cookie
        Jenga.Common.Errors
        Jenga.Common.HasJengaConfig
        Jenga.Common.ScrubPrefix
        Jenga.Common.Stripe
        Jenga.Common.Log

  default-language: Haskell2010
  ghc-options: -Wall -Werror -O -fno-show-valid-hole-fits
               -Wunused-packages

               -- -Wredundant-constraints -Wincomplete-uni-patterns -Wincomplete-record-updates -O -fno-show-valid-hole-fits -Werror=incomplete-patterns

  default-extensions:
      AllowAmbiguousTypes
      BangPatterns
      ConstraintKinds
      DataKinds
      DefaultSignatures
      DeriveDataTypeable
      DeriveFoldable
      DeriveFunctor
      DeriveGeneric
      DeriveTraversable
      EmptyCase
      EmptyDataDecls
      FlexibleContexts
      FlexibleInstances
      FunctionalDependencies
      GADTs
      GeneralizedNewtypeDeriving
      InstanceSigs
      KindSignatures
      LambdaCase
      MultiParamTypeClasses
      OverloadedStrings
      PolyKinds
      QuasiQuotes
      RankNTypes
      RecursiveDo
      ScopedTypeVariables
      StandaloneDeriving
      TemplateHaskell
      TypeApplications
      TypeFamilies
      TypeOperators
      UndecidableInstances
