cabal-version:      3.0
name:               reflex-effectful
version:            0.1.0.0
synopsis:           Effectful-based interface for reflex-dom
license:            BSD-3-Clause
build-type:         Simple

library
  exposed-modules:
    Reflex.Effectful
    Reflex.Effectful.Types
    Reflex.Effectful.Effect.Sample
    Reflex.Effectful.Effect.Hold
    Reflex.Effectful.Effect.PostBuild
    Reflex.Effectful.Effect.TriggerEvent
    Reflex.Effectful.Effect.PerformEvent
    Reflex.Effectful.Effect.Adjustable
    Reflex.Effectful.Effect.Dom
    Reflex.Effectful.Effect.Prerender
    Reflex.Effectful.Effect.JSM
    Reflex.Effectful.Effect.HasDocument
    Reflex.Effectful.Effect.DomRenderHook
    Reflex.Effectful.Effect.EventWriter
    Reflex.Effectful.Effect.NotReady
    Reflex.Effectful.Effect.DynamicWriter
    Reflex.Effectful.Effect.BehaviorWriter
    Reflex.Effectful.Effect.Requester
    Reflex.Effectful.Run
    Reflex.Effectful.Jenga
    Reflex.Effectful.Effect.Jenga.Configs
    Reflex.Effectful.Effect.Jenga.Cookies
    Reflex.Effectful.Effect.Jenga.Route

  other-modules:
    Reflex.Effectful.Internal.Channel
    Reflex.Effectful.Internal.Interpret
    Reflex.Effectful.Internal.WidgetLoop
    Reflex.Effectful.Internal.Main

  build-depends:
    , base            >=4.12 && <5
    , bytestring
    , containers
    , data-default
    , dependent-map
    , dependent-sum
    , effectful-core   >=2.3
    , ghcjs-dom
    , jsaddle
    , lens
    , patch
    , reflex
    , reflex-dom-core
    , text
    , time

  hs-source-dirs:   src
  default-language:  Haskell2010
  ghc-options:       -Wall

  default-extensions:
    ConstraintKinds
    DataKinds
    FlexibleContexts
    FlexibleInstances
    GADTs
    KindSignatures
    MultiParamTypeClasses
    RankNTypes
    ScopedTypeVariables
    TypeApplications
    TypeFamilies
    TypeOperators

executable counter-example
  main-is:          Counter.hs
  hs-source-dirs:   examples
  build-depends:
    , base
    , containers
    , data-default
    , jsaddle
    , jsaddle-warp
    , lens
    , reflex
    , reflex-dom-core
    , reflex-effectful
    , text
  default-language:  Haskell2010
  ghc-options:       -threaded
  default-extensions:
    DataKinds
    FlexibleContexts
    OverloadedStrings
    TypeOperators
  if arch(javascript) || arch(wasm32)
    buildable: False
